package gui;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;

/**
 *
 * @author mikig
 */
public class Window extends javax.swing.JFrame {

    static MenuPanel menuPanel;
    static GamePanel gamePanel;
    private static final Window WINDOW= new Window();
    /**
     * Creates new form gui.Window
     */
    private Window() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    public static Window getInstance(){
        return WINDOW;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("8K");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gui/Graphics/mountain.png")).getImage());
        setName("gameWindow"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 1024));
        pack();
        setResizable(false);
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        Window window = getInstance();
        menuPanel = MenuPanel.getInstance();
        menuPanel.setVisible(true);
        window.add(menuPanel);

        window.setVisible(true);
    }

    public static void gameStart(){
        menuPanel.setVisible(false);
        WINDOW.remove(menuPanel);
        gamePanel = new GamePanel();
        WINDOW.add(gamePanel);
        gamePanel.setVisible(true);
    }

    public static void exitToMenu(){
        gamePanel.setVisible(false);
        WINDOW.remove(gamePanel);
        gamePanel = null;
        WINDOW.add(menuPanel);
        menuPanel.setVisible(true);
    }

    // Variables declaration - do not modify
    // End of variables declaration
}
