package gui;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import util.HibernateUtil;

import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;

/**
 *
 * @author mikig
 */
public class Window extends javax.swing.JFrame {

    static MenuPanel menuPanel;
    static GamePanel gamePanel;
    static ScoreBoardPanel scoreBoardPanel;
    static boolean isDataBaseConnected = true;
    private static final Window WINDOW= new Window();
    /**
     * Creates new form gui.Window
     */
    private Window() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
//        try{
//            HibernateUtil.getSessionFactory();
//        } catch (Exception e){
//            isDataBaseConnected = false;
//        }
    }

    public static Window getInstance(){
        return WINDOW;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("8K");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gui/Graphics/mountain.png")).getImage());
        setName("gameWindow"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 1024));
        pack();
        setResizable(false);
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        String url = "jdbc:mysql://localhost:3306?serverTimezone=CET"; //pointing to no database.
        String username = "root";
        String password = "root1234";
        try (Connection connection = DriverManager.getConnection(url, username, password)) {
            if(connection != null) connection.close();
        } catch (Exception e){
            Window.isDataBaseConnected = false;
        }
        Window window = getInstance();
        menuPanel = MenuPanel.getInstance();
        menuPanel.setVisible(true);
        window.add(menuPanel);

        window.setVisible(true);



    }

    public static void gameStart(){
        menuPanel.setVisible(false);
        WINDOW.remove(menuPanel);
        if(scoreBoardPanel != null){
            scoreBoardPanel.setVisible(false);
            WINDOW.remove(scoreBoardPanel);
        }
        gamePanel = new GamePanel();
        WINDOW.add(gamePanel);
        gamePanel.setVisible(true);
    }

    public static void exitToMenu(){
        if(gamePanel != null){
            gamePanel.setVisible(false);
            WINDOW.remove(gamePanel);
        }
        if(scoreBoardPanel != null){
            scoreBoardPanel.setVisible(false);
            WINDOW.remove(scoreBoardPanel);
        }
        gamePanel = null;
        WINDOW.add(menuPanel);
        menuPanel.setVisible(true);
    }

    public static void scoreBoard(int score){
        if(gamePanel != null){
            gamePanel.setVisible(false);
            WINDOW.remove(gamePanel);
        }

        menuPanel.setVisible(false);
        if(score == 0){
            scoreBoardPanel = ScoreBoardPanel.getInstance();
        } else{
            scoreBoardPanel = ScoreBoardPanel.getInstance(score);
        }

        WINDOW.remove(menuPanel);
        WINDOW.add(scoreBoardPanel);
        scoreBoardPanel.setVisible(true);
    }



    // Variables declaration - do not modify
    // End of variables declaration
}
